[build]
  command = "vite build"
  publish = "dist"

[build.environment]
  # Tell Netlify to ignore specific env vars during secrets scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_SUPABASE_PROJECT_ID,VITE_SUPABASE_PUBLISHABLE_KEY,VITE_SUPABASE_URL"
