name: AI Codegen from Issue
on:
  issues:
    types: [labeled]      # runs when a label is added
  workflow_dispatch:      # also allow manual runs

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  codegen:
    # run only when the newly added label is "codegen" OR manual run
    if: (github.event_name == 'issues' && github.event.action == 'labeled' && github.event.label.name == 'codegen') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create feature branch
        id: branch
        run: |
          TITLE="${{ github.event_name == 'workflow_dispatch' && 'manual-run' || github.event.issue.title }}"
          SAFE_TITLE="$(echo "$TITLE" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')"
          BR="feature/codegen-${SAFE_TITLE}-${{ github.event_name == 'workflow_dispatch' && 'manual' || github.event.issue.number }}"
          git checkout -b "$BR"
          echo "BRANCH=$BR" >> $GITHUB_OUTPUT

      # 🧠 Run Aider to make code changes based on the Issue text
      - name: Apply changes with Aider
        uses: mirrajabi/aider-github-action@v1.1.0
        timeout-minutes: 15
        with:
          api_key_env_name: OPENAI_API_KEY
          api_key_env_value: ${{ secrets.OPENAI_API_KEY }}
          branch: ${{ steps.branch.outputs.BRANCH }}
          # Keep it safe & focused on your Lovable/React app
          model: gpt-4o-mini
          aider_args: >-
            --yes
            --message "You are adding/modifying code for a React/TypeScript currency-converter app.
            Source of truth is the GitHub Issue below. Create or update files only under src/ or app/.
            Keep behavior safe and typed. Add small tests when obvious. Do not touch tooling/CI configs.
            Issue Title: ${{ github.event.issue.title }}
            Issue Body:
            ${{ github.event.issue.body }}"

      - name: Push branch
        run: git push --set-upstream origin "${{ steps.branch.outputs.BRANCH }}"

      - name: Open pull request
        uses: peter-evans/create-pull-request@v6
        with:
          branch: "${{ steps.branch.outputs.BRANCH }}"
          title: "AI codegen: ${{ github.event.issue.title }}"
          body: "Generated from issue #${{ github.event.issue.number }} (label: `codegen`). Please review carefully."
          base: "main"
