name: AI Codegen from Issue

on:
  issues:
    types: [opened, edited, labeled, reopened]

permissions:
  contents: write
  pull-requests: write
  issues: read

jobs:
  ai-codegen:
    # ✅ Check the issue labels directly (no matrix needed)
    if: contains(github.event.issue.labels.*.name, 'codegen')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Create feature branch
        id: branch
        run: |
          SAFE_TITLE="$(echo "${{ github.event.issue.title }}" | tr ' ' '-' | tr -cd '[:alnum:]-' | tr '[:upper:]' '[:lower:]')"
          BR="feature/codegen-${SAFE_TITLE}-${{ github.event.issue.number }}"
          git checkout -b "$BR"
          echo "branch=$BR" >> $GITHUB_OUTPUT

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (if any)
        run: |
          if [ -f package.json ]; then
            npm ci --ignore-scripts || npm i --ignore-scripts
          fi

      - name: Generate code with AI (repo-scoped)
        uses: cognitivecomputations/ai-github-action@v1
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: "repo"
          instructions: |
            You are scaffolding code for a
